name: 'ServerPilot'
description: 'Interface with the ServerPilot API via a GitHub Action'
inputs:
  client_id:
    description: 'Your ServerPilot client ID for the API connection'
    required: true
    default: ''
  api_key:
    description: 'Your ServerPilot API Key for the API connection'
    required: true
    default: ''
  system_user:
    description: 'The ServerPilot user to operate as when running commands'
    required: true
    default: ''
  action:
    description: 'The action to perform your ServerPilot account'
    required: true
    default: ''
  app_name:
    description: 'The name of the app to create or remove'
    required: true
    default: null
  php_version:
    description: 'What the PHP version should be if we are creating a new app'
    required: false
    default: "7.1"
  ssl:
    description: 'Enables an SSL if we are creating a new app'
    required: false
    default: true
  db:
    description: 'Creates a new database if we are creating a new app'
    required: false
    default: true
  domains:
    description: 'The domains to use for this app if we are creating a new one'
    required: false
    default: []
runs:
  using: 'node12'
  main: 'index.js'
