on: push

jobs:
  test_run:
    runs-on: ubuntu-latest
    name: ServerPilot
    steps:
    - name: Tests the creation action
      uses: trendyminds/github-actions-serverpilot@master
      with:
        action: 'create'
        client_id: ${{secrets.SERVERPILOT_CLIENT_ID}}
        api_key: ${{secrets.SERVERPILOT_API_KEY}}
        system_user: ${{secrets.SERVERPILOT_SYSTEM_USER}}
        app_name: 'mytestapp'
        php_version: '7.2'
        ssl: true
        db: true
        domains: ["mytestapp.trendyminds.io"]
